Repository googleapis/java-compute, pull requests merged in 2020-12, with the labels that each got.

#254 chore: ignore generated client files in metadata
  synth.metadata
Labels: api: compute, cla: yes

#256 chore: regenerate common templates
  .github/CODEOWNERS
  .github/blunderbuss.yml
  .github/generated-files-bot.yml
  .github/readme/synth.py
  .github/snippet-bot.yml
  .github/workflows/approve-readme.yaml
  .github/workflows/auto-release.yaml
  .github/workflows/formatting.yaml
  .github/workflows/samples.yaml
  .kokoro/build.sh
  .kokoro/common.sh
  .kokoro/continuous/readme.cfg
  .kokoro/readme.sh
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/stage.cfg
  .kokoro/release/stage.sh
  CODE_OF_CONDUCT.md
  synth.metadata
Labels: api: compute, cla: yes, context: full

#257 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: compute, automerge, cla: yes

#259 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: compute, automerge, cla: yes

#261 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: compute, automerge, cla: yes

#268 ci(java): ignore bot users for generate-files-bot
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: compute, automerge, cla: yes, context: full

#269 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: compute, automerge, cla: yes

#271 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: compute, automerge, cla: yes

#275 chore(java): remove formatter action
  .github/workflows/formatting.yaml
  synth.metadata
Labels: api: compute, automerge, cla: yes, context: full, merge
