Repository googleapis/java-compute, pull requests merged in 2020-04, with the labels that each got.

#95 test: fix integration tests
  src/test/java/com/google/cloud/compute/v1/it/ITComputeTest.java
Labels: cla: yes

#98 chore: stop version managing grpc
  pom.xml
Labels: cla: yes

#101 deps: update core
  pom.xml
Labels: cla: yes

#111 chore: easymock should be a test dependency
  pom.xml
Labels: cla: yes

#109 chore: release 0.117.1-SNAPSHOT
  pom.xml
  versions.txt
Labels: cla: yes, type: process

#118 chore: update common templates
  .kokoro/common.sh
  .kokoro/nightly/integration.cfg
  README.md
  synth.metadata
Labels: automerge, cla: yes

#125 chore: update common templates
  .kokoro/common.sh
  .kokoro/dependencies.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  .kokoro/presubmit/integration.cfg
  .kokoro/presubmit/samples.cfg
  synth.metadata
Labels: automerge, cla: yes

#131 refactor(test): rewrite InstanceGroupManager test to insert then list
  src/test/java/com/google/cloud/compute/v1/it/ITComputeTest.java
  src/test/java/com/google/cloud/compute/v1/it/ITInstanceGroupManagerTest.java
Labels: cla: yes

#128 chore(java): allow overriding the versioning section of the Java README (#495)
  README.md
  synth.metadata
Labels: automerge, cla: yes

#135 chore: regenerate README
  README.md
  synth.metadata
Labels: automerge, cla: yes

#136 chore: regenerate README
  README.md
  synth.metadata
Labels: automerge, cla: yes
