Repository googleapis/java-compute, pull requests merged in 2021-07, with the labels that each got.

#478 fix: Add shopt -s nullglob to dependencies script
  .kokoro/coerce_logs.sh
  .kokoro/dependencies.sh
  synth.metadata
Labels: api: compute, automerge, cla: yes, context: full

#481 chore: remove distributionManagement section
  pom.xml
Labels: api: compute, automerge, cla: yes

#483 chore: release v1.3.0-alpha
  google-cloud-compute-bom/pom.xml
  google-cloud-compute/pom.xml
  pom.xml
  proto-google-cloud-compute-v1/pom.xml
  versions.txt
Labels: api: compute, automerge, autorelease: pending, cla: yes

#486 chore: remove distributionManagement section from BOM
  google-cloud-compute-bom/pom.xml
  pom.xml
Labels: api: compute, automerge, cla: yes

#488 chore: release v1.3.0-alpha
  google-cloud-compute-bom/pom.xml
  google-cloud-compute/pom.xml
  pom.xml
  proto-google-cloud-compute-v1/pom.xml
  versions.txt
Labels: api: compute, automerge, autorelease: pending, cla: yes

#492 chore: remove All rights reserved clause from java.header
  java.header
  synth.metadata
Labels: api: compute, automerge, cla: yes, context: full

#493 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: compute, automerge, cla: yes

#496 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: compute, automerge, cla: yes

#497 chore: add dependencyDashboardLabels to renovate.json
  renovate.json
  synth.metadata
Labels: api: compute, automerge, cla: yes, context: full

#500 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: compute, automerge, cla: yes
