Repository googleapis/java-compute, pull requests merged in 2021-06, with the labels that each got.

#436 tests: add new tests
  google-cloud-compute/src/test/java/com/google/cloud/compute/v1/integration/BaseTest.java
  google-cloud-compute/src/test/java/com/google/cloud/compute/v1/integration/ITAddressesTest.java
  google-cloud-compute/src/test/java/com/google/cloud/compute/v1/integration/ITSmokeInstancesTest.java
Labels: api: compute, cla: yes

#451 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: compute, automerge, cla: yes

#452 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: compute, automerge, cla: yes

#459 chore: remove legacy format check
  .github/workflows/formatting.yaml
Labels: api: compute, automerge, cla: yes

#460 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: compute, automerge, cla: yes

#462 chore: dump maven version along with java
  .kokoro/build.sh
  synth.metadata
Labels: api: compute, cla: yes, context: full

#466 fix: Update dependencies.sh to not break on mac
  .kokoro/dependencies.sh
  synth.metadata
Labels: api: compute, automerge, cla: yes, context: full

#465 chore: update README to add example code
  .readme-partials.yaml
  .repo-metadata.json
  README.md
Labels: api: compute, automerge, cla: yes

#468 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: compute, automerge, cla: yes

#469 chore: add AC Tools team as codeowner
  .github/CODEOWNERS
  .github/sync-repo-settings.yaml
  .repo-metadata.json
Labels: api: compute, automerge, cla: yes

#471 chore: update pom
  samples/install-without-bom/pom.xml
Labels: api: compute, automerge, cla: yes

#472 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: compute, automerge, cla: yes
