Repository googleapis/java-compute, pull requests merged in 2021-05, with the labels that each got.

#393 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: compute, automerge, cla: yes, context: none

#391 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: compute, automerge, cla: yes

#407 chore: Update google-cloud-shared-dependencies dependency to 1.1.0
  google-cloud-compute/pom.xml
  pom.xml
Labels: api: compute, cla: yes

#417 fix: fix fields serialization for cases when the field name start with a capital letter
  google-cloud-compute/src/test/java/com/google/cloud/compute/v1/ForwardingRulesClientTest.java
  google-cloud-compute/src/test/java/com/google/cloud/compute/v1/GlobalForwardingRulesClientTest.java
  google-cloud-compute/src/test/java/com/google/cloud/compute/v1/NetworksClientTest.java
  proto-google-cloud-compute-v1/src/main/java/com/google/cloud/compute/v1/Allowed.java
  proto-google-cloud-compute-v1/src/main/java/com/google/cloud/compute/v1/AllowedOrBuilder.java
  proto-google-cloud-compute-v1/src/main/java/com/google/cloud/compute/v1/Compute.java
  proto-google-cloud-compute-v1/src/main/java/com/google/cloud/compute/v1/Denied.java
  proto-google-cloud-compute-v1/src/main/java/com/google/cloud/compute/v1/DeniedOrBuilder.java
  proto-google-cloud-compute-v1/src/main/java/com/google/cloud/compute/v1/ForwardingRule.java
  proto-google-cloud-compute-v1/src/main/java/com/google/cloud/compute/v1/ForwardingRuleOrBuilder.java
  proto-google-cloud-compute-v1/src/main/java/com/google/cloud/compute/v1/Network.java
  proto-google-cloud-compute-v1/src/main/java/com/google/cloud/compute/v1/NetworkOrBuilder.java
  proto-google-cloud-compute-v1/src/main/java/com/google/cloud/compute/v1/PacketMirroringFilter.java
  proto-google-cloud-compute-v1/src/main/java/com/google/cloud/compute/v1/PacketMirroringFilterOrBuilder.java
  proto-google-cloud-compute-v1/src/main/proto/google/cloud/compute/v1/compute.proto
  synth.metadata
Labels: api: compute, cla: yes

#419 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: compute, automerge, cla: yes, context: full

#416 chore: release java-compute v1.1.1-alpha-SNAPSHOT
  README.md
  google-cloud-compute-bom/pom.xml
  google-cloud-compute/pom.xml
  pom.xml
  proto-google-cloud-compute-v1/pom.xml
  versions.txt
Labels: api: compute, cla: yes

#421 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: compute, automerge, cla: yes, context: full

#422 chore: release java-compute v1.1.1-alpha
  README.md
  google-cloud-compute-bom/pom.xml
  google-cloud-compute/pom.xml
  pom.xml
  proto-google-cloud-compute-v1/pom.xml
  versions.txt
Labels: api: compute, automerge, autorelease: pending, cla: yes

#424 chore: release 1.1.2-alpha-SNAPSHOT
  README.md
  google-cloud-compute-bom/pom.xml
  google-cloud-compute/pom.xml
  pom.xml
  proto-google-cloud-compute-v1/pom.xml
  versions.txt
Labels: api: compute, automerge, cla: yes

#425 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: compute, automerge, cla: yes, context: full

#427 build: fix release-please config format
  .github/release-please.yml
Labels: api: compute, automerge, cla: yes

#435 chore: dump maven version along with java
  .kokoro/build.sh
  synth.metadata
Labels: api: compute, automerge, cla: yes, context: full

#433 chore: release java-compute v1.2.0-alpha
  README.md
  google-cloud-compute-bom/pom.xml
  google-cloud-compute/pom.xml
  pom.xml
  proto-google-cloud-compute-v1/pom.xml
  versions.txt
Labels: api: compute, automerge, autorelease: pending, cla: yes

#403 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: compute, automerge, cla: yes

#441 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: compute, automerge, cla: yes
