Repository googleapis/java-compute, pull requests merged in 2021-02, with the labels that each got.

#278 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: compute, automerge, cla: yes

#312 chore: Re-generated to pick up changes from synthtool.
  .github/workflows/auto-release.yaml
  .github/workflows/ci.yaml
  .kokoro/linkage-monitor.sh
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  LICENSE
  synth.metadata
Labels: api: compute, cla: yes, context: partial

#320 test: allow cleanup to temporarily fail
  src/test/java/com/google/cloud/compute/v1/it/BaseTest.java
Labels: api: compute, automerge, cla: yes

#316 chore: update javadoc config link
  pom.xml
Labels: api: compute, cla: yes

#319 test: commit integration tests by georgiyekkert
  google-cloud-compute/pom.xml
  google-cloud-compute/src/test/java/com/google/cloud/compute/v1/integration/BaseTest.java
  google-cloud-compute/src/test/java/com/google/cloud/compute/v1/integration/ITAddressesTest.java
  google-cloud-compute/src/test/java/com/google/cloud/compute/v1/integration/ITPaginationTest.java
  google-cloud-compute/src/test/java/com/google/cloud/compute/v1/integration/ITSmokeInstancesTest.java
  google-cloud-compute/src/test/java/com/google/cloud/compute/v1/integration/README.md
Labels: api: compute, automerge, cla: yes

#321 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: compute, automerge, cla: yes

#315 ci: linkage monitor CI job to use build.sh
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: compute, automerge, cla: yes, context: full

#327 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: compute, automerge, cla: yes
