Repository googleapis/java-compute, pull requests merged in 2021-11, with the labels that each got.

#576 chore(java): remove pin on Apache Maven 3.8.1 from github actions
  .github/workflows/ci.yaml
  synth.metadata
Labels: cla: yes, api: compute, automerge, context: full

#577 chore: update ci.yaml
  .github/workflows/ci.yaml
  synth.metadata
Labels: cla: yes, api: compute, automerge, context: full

#580 ci: re-generated to pick up changes from synthtool.
  .github/workflows/ci.yaml
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: cla: yes, api: compute, context: full

#574 tests: add test for headers in compute
  google-cloud-compute/src/test/java/com/google/cloud/compute/v1/integration/ITHeadersTest.java
  google-cloud-compute/src/test/java/com/google/cloud/compute/v1/integration/ITPaginationTest.java
Labels: cla: yes, api: compute

#582 chore: remove enable-samples profile
  .kokoro/build.sh
  CONTRIBUTING.md
  synth.metadata
Labels: cla: yes, api: compute, context: full, samples
