Repository googleapis/java-compute, pull requests merged in 2021-03, with the labels that each got.

#333 chore: add ignore tag to flaky tests
  src/test/java/com/google/cloud/compute/v1/it/ITDiskTest.java
  src/test/java/com/google/cloud/compute/v1/it/ITFirewallTest.java
  src/test/java/com/google/cloud/compute/v1/it/ITNetworkTest.java
Labels: api: compute, automerge, cla: yes

#328 chore: update cloud-rad buckets
  .kokoro/build.sh
  .kokoro/dependencies.sh
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: compute, automerge, cla: yes, context: full

#330 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: compute, cla: yes

#339 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: compute, automerge, cla: yes

#340 ci: skip flaky tests until diregapic
  src/test/java/com/google/cloud/compute/v1/it/ITDiskTest.java
  src/test/java/com/google/cloud/compute/v1/it/ITFirewallTest.java
  src/test/java/com/google/cloud/compute/v1/it/ITNetworkTest.java
Labels: api: compute, automerge, cla: yes

#341 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: compute, automerge, cla: yes

#342 chore: remove docLava v2 doc generation
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: api: compute, automerge, cla: yes, context: full

#344 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: compute, automerge, cla: yes

#348 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: compute, automerge, cla: yes

#349 chore: copy README to docfx-yml dir
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: compute, automerge, cla: yes, context: full

#351 build(java): update autorelease title check in response to the new multi release branch changes
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: compute, automerge, cla: yes, context: full

#357 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: compute, automerge, cla: yes

#359 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: compute, automerge, cla: yes

#362 chore(java): detect sample-secrets in build.sh
  .kokoro/build.sh
  synth.metadata
Labels: api: compute, build.sh, cla: yes, context: full, in, sample-secrets, samples

#363 chore: remove staging bucket v2
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: api: compute, automerge, cla: yes, context: full
